/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../@angular/core';
import * as import1 from './dynamic-load.module';
class DynamicLoadModuleInjector extends import0.ɵNgModuleInjector<import1.DynamicLoadModule> {
  _DynamicLoadModule_0:import1.DynamicLoadModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.DynamicLoadModule {
    this._DynamicLoadModule_0 = new import1.DynamicLoadModule();
    return this._DynamicLoadModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.DynamicLoadModule)) { return this._DynamicLoadModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DynamicLoadModuleNgFactory:import0.NgModuleFactory<import1.DynamicLoadModule> = new import0.NgModuleFactory<any>(DynamicLoadModuleInjector,import1.DynamicLoadModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RlbmlzL0RvY3VtZW50cy9wcm9qZWN0cy93Y20tdGVtcGxhdGUtbWFuYWdlci1uZzIvc3JjL2R5bmFtaWMtbG9hZC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZGVuaXMvRG9jdW1lbnRzL3Byb2plY3RzL3djbS10ZW1wbGF0ZS1tYW5hZ2VyLW5nMi9zcmMvZHluYW1pYy1sb2FkLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
