/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './dynamic-load.module';
import * as import2 from '@angular/core/src/di/injector';
class DynamicLoadModuleInjector extends import0.NgModuleInjector<import1.DynamicLoadModule> {
  _DynamicLoadModule_0:import1.DynamicLoadModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.DynamicLoadModule {
    this._DynamicLoadModule_0 = new import1.DynamicLoadModule();
    return this._DynamicLoadModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.DynamicLoadModule)) { return this._DynamicLoadModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DynamicLoadModuleNgFactory:import0.NgModuleFactory<import1.DynamicLoadModule> = new import0.NgModuleFactory(DynamicLoadModuleInjector,import1.DynamicLoadModule);