/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../@angular/core';
import * as import1 from './dynamic-load.component';
import * as import2 from './dynamic-load.service';
const styles_DynamicLoadComponent:any[] = ['[_nghost-%COMP%] { display: block; }'];
export const RenderType_DynamicLoadComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_DynamicLoadComponent,
  data: {}
}
);
export function View_DynamicLoadComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
function View_DynamicLoadComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(8388608,(null as any),(null as any),1,'app-dynamic-load',([] as any[]),(null as any),(null as any),(null as any),View_DynamicLoadComponent_0,RenderType_DynamicLoadComponent)),
    import0.ɵdid(352256,(null as any),0,import1.DynamicLoadComponent,[
      import0.ViewContainerRef,
      import0.ComponentFactoryResolver,
      import2.DynamicLoadService
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const DynamicLoadComponentNgFactory:import0.ComponentFactory<import1.DynamicLoadComponent> = import0.ɵccf('app-dynamic-load',import1.DynamicLoadComponent,View_DynamicLoadComponent_Host_0,{
  componentData: 'componentData',
  type: 'type'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RlbmlzL0RvY3VtZW50cy9wcm9qZWN0cy93Y20tdGVtcGxhdGUtbWFuYWdlci1uZzIvc3JjL2R5bmFtaWMtbG9hZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZGVuaXMvRG9jdW1lbnRzL3Byb2plY3RzL3djbS10ZW1wbGF0ZS1tYW5hZ2VyLW5nMi9zcmMvZHluYW1pYy1sb2FkLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2RlbmlzL0RvY3VtZW50cy9wcm9qZWN0cy93Y20tdGVtcGxhdGUtbWFuYWdlci1uZzIvc3JjL2R5bmFtaWMtbG9hZC5jb21wb25lbnQudHMuRHluYW1pY0xvYWRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLWR5bmFtaWMtbG9hZD48L2FwcC1keW5hbWljLWxvYWQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQUE7Ozs7SUFBQTtLQUFBOzs7Ozs7OzsifQ==
